### ISSUE TITLE
GPS coordinates precision and location

### ISSUE THREAD

**Issue by 13rac1** [badcamp/badcamp2016-splash#3]
This came up in the meeting, the GPS coordinates have inconsistent precision.
`37.8715926  -122.27274699999998`

Currently this coordinate is in the middle of University Ave: https://www.google.com/maps/place/37%C2%B052'17.7%22N+122%C2%B016'21.9%22W/@37.8715926,-122.2749357,17z/data=!4m2!3m1!1s0x0:0x0 If it's going to be so precise, it really should point to the actual location.

I personally prefer the `37°52'17.7"N 122°16'21.9"W` format.

**Comment by fluxsauce** [comment]
Fixed, thanks! https://github.com/badcamp/badcamp2016-splash/commit/2be1e23a52e97a3fe0002726e9f01a27d1c57cfa

**Comment by 13rac1** [comment]
It's still in the middle of University Ave, but if that's the location, so be it. ;)

**Comment by fluxsauce** [comment]
@eosrei

**Comment by fluxsauce** [comment]
@eosrei fair point.

37° 52' 18.8358" -122° 15' 38.6388"

https://www.google.com/maps/place/37%C2%B052'18.8%22N+122%C2%B015'38.6%22W/@37.8718988,-122.262927,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0x0

**Comment by 13rac1** [comment]
Works for me! Haha!
